(ns uml-viewer.application.ir-generator
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.pprint :as pprint]
            [clojure.string :as str]
            [uml-viewer.graph :as graph]
            [uml-viewer.domain.policy :as policy])
  (:import [java.nio.file Files StandardCopyOption AtomicMoveNotSupportedException]))

(defn read-policy [path]
  (edn/read-string (slurp path)))

(defn emit [doc]
  (str ";; Generated by clj -M:ir from the policy file. Do not edit.\n"
       (binding [*print-namespace-maps* false
                 *print-length* nil
                 *print-level* nil
                 pprint/*print-right-margin* 90]
         (with-out-str (pprint/pprint doc)))))

(defn- scan-options [policy]
  (merge {:prefix (or (:prefix policy) "uml-viewer")}
         (select-keys policy [:modules])))

(defn- policy-reference [policy-path out-path]
  (let [policy (.toPath (.getCanonicalFile (io/file policy-path)))
        parent (.getParent (.toPath (.getCanonicalFile (io/file out-path))))]
    (try
      (str/replace (str (.relativize parent policy)) "\\" "/")
      (catch IllegalArgumentException _ (str policy)))))

(defn- write-document! [path doc]
  (let [target (.toPath (.getAbsoluteFile (io/file path)))
        parent (.getParent target)]
    (Files/createDirectories parent (make-array java.nio.file.attribute.FileAttribute 0))
    (let [temp (Files/createTempFile parent ".uml-" ".edn"
                                     (make-array java.nio.file.attribute.FileAttribute 0))]
      (try
        (spit (.toFile temp) (emit doc) :encoding "UTF-8")
        (try
          (Files/move temp target (into-array StandardCopyOption
                                             [StandardCopyOption/ATOMIC_MOVE
                                              StandardCopyOption/REPLACE_EXISTING]))
          (catch AtomicMoveNotSupportedException _
            (Files/move temp target (into-array StandardCopyOption
                                               [StandardCopyOption/REPLACE_EXISTING]))))
        (finally (Files/deleteIfExists temp))))))

(defn document
  "Scan source with `graph-impl` and apply `policy`. Returns the IR document."
  [graph-impl policy]
  (let [root (or (:src policy) "src")
        opts (scan-options policy)
        graph (graph/scan graph-impl root opts)]
    (policy/apply-policy policy graph)))

(defn generate
  "Write the IR document for `policy-path` using `graph-impl`. Returns the output path."
  ([graph-impl policy-path] (generate graph-impl policy-path nil))
  ([graph-impl policy-path out-path]
   (let [policy (read-policy policy-path)
         graph (graph/scan graph-impl
                           (or (:src policy) "src")
                           (scan-options policy))
         extra (policy/unassigned policy graph)
         out (or out-path (:out policy) "examples/uml-viewer.edn")
         doc (assoc (policy/apply-policy policy graph)
               :policy-file (policy-reference policy-path out)
               :diagnostics (vec (:diagnostics graph)))]
     (when (seq extra)
       (binding [*out* *err*]
         (println "Unassigned namespaces:"
                  (str/join ", " (map :ns extra)))))
     (when (seq (:diagnostics graph))
       (binding [*out* *err*]
         (println "Source diagnostics:" (count (:diagnostics graph))
                  "(recorded in the generated EDN)")))
     (write-document! out doc)
     out)))
